baseURL = "https://vimproved.dev/"

theme = "bearblog"

title = "vimproved"
author = "Violet Purcell"
copyright = "This website is licensed under [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) (content) and [AGPL-3.0](https://www.gnu.org/licenses/agpl-3.0.en.html) (code)"
languageCode = "en-US"

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
blog = "/:slug/"
tags = "/blog/:slug"

[params]
description = "violet's personal website"

title = "vimproved"

hideMadeWithLine = true

dateFormat = "2006-01-02"
